In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("car data.csv")

In [7]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [8]:
import sklearn
sklearn.__version__

'1.6.1'

In [14]:
X = df.drop("Selling_Price", axis="columns")
y = df['Selling_Price']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
X_train.shape

(240, 8)

In [10]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
oe

OrdinalEncoder()

In [18]:
X_train['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [29]:
oe.fit_transform(X_train[['Transmission']]) # [[]] this is used, as only matrix expected

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [27]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
ohe.fit_transform(X_train[['Fuel_Type']])

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [28]:
ohe.categories_

[array(['CNG', 'Diesel', 'Petrol'], dtype=object)]

In [37]:
from sklearn.impute import SimpleImputer
# si = SimpleImputer(strategy='mean', missing_values=np.nan)
mean_si = SimpleImputer(missing_values=np.nan, strategy='mean')
mean_si

SimpleImputer()

In [33]:
X_train.isnull().sum()

Car_Name         0
Year             0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [31]:
si.get_params()

{'add_indicator': False,
 'copy': True,
 'fill_value': None,
 'keep_empty_features': False,
 'missing_values': nan,
 'strategy': 'mean'}

In [35]:
med_si = SimpleImputer(missing_values=np.nan, strategy='median')
med_si

SimpleImputer(strategy='median')

In [38]:
med_si.fit_transform(X_train[['Kms_Driven']])

array([[ 26000.],
       [  3500.],
       [ 50000.],
       [ 36000.],
       [  8700.],
       [ 41000.],
       [ 40000.],
       [ 18796.],
       [ 75000.],
       [ 51439.],
       [ 50000.],
       [ 28569.],
       [ 40534.],
       [ 23709.],
       [ 35000.],
       [  5000.],
       [ 12900.],
       [ 35000.],
       [ 21780.],
       [ 14465.],
       [ 31604.],
       [197176.],
       [ 11000.],
       [ 53460.],
       [   500.],
       [  5400.],
       [ 41442.],
       [ 50000.],
       [ 89000.],
       [ 17000.],
       [  1900.],
       [ 56001.],
       [ 43000.],
       [  2135.],
       [500000.],
       [ 87934.],
       [ 88000.],
       [ 24678.],
       [127000.],
       [ 41678.],
       [ 40000.],
       [ 44000.],
       [ 69562.],
       [ 59000.],
       [ 22517.],
       [ 12000.],
       [ 54200.],
       [ 30000.],
       [ 13000.],
       [ 16002.],
       [ 25000.],
       [ 35500.],
       [ 21000.],
       [ 29000.],
       [ 11849.],
       [ 4

In [39]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler() # (value - mean)/sigma
ss

StandardScaler()

In [40]:
ss.fit_transform(X_train[['Kms_Driven']])

array([[-0.27555466],
       [-0.81428242],
       [ 0.29908829],
       [-0.0361201 ],
       [-0.68977645],
       [ 0.08359718],
       [ 0.05965372],
       [-0.44804332],
       [ 0.89767469],
       [ 0.33354292],
       [ 0.29908829],
       [-0.21404392],
       [ 0.07243953],
       [-0.33040912],
       [-0.06006356],
       [-0.77836724],
       [-0.58921394],
       [-0.06006356],
       [-0.37659605],
       [-0.55174243],
       [-0.14137553],
       [ 3.82299039],
       [-0.6347065 ],
       [ 0.38193264],
       [-0.88611279],
       [-0.76878986],
       [ 0.09418019],
       [ 0.29908829],
       [ 1.23288307],
       [-0.49104577],
       [-0.85259195],
       [ 0.44277297],
       [ 0.13148409],
       [-0.84696524],
       [11.07364355],
       [ 1.20735935],
       [ 1.20893962],
       [-0.30720791],
       [ 2.14273441],
       [ 0.09983084],
       [ 0.05965372],
       [ 0.15542755],
       [ 0.76747017],
       [ 0.51457939],
       [-0.35894972],
       [-0

In [41]:
from sklearn.pipeline import Pipeline

In [49]:
st = [("Impute_mode", SimpleImputer(missing_values=np.nan, strategy="most_frequent")), 
      ("OHE", OneHotEncoder(sparse_output=False)), 
      ("Scaling", StandardScaler())]

pipe = Pipeline(steps = st).set_output(transform="pandas")
pipe


Pipeline(steps=[('Impute_mode', SimpleImputer(strategy='most_frequent')),
                ('OHE', OneHotEncoder(sparse_output=False)),
                ('Scaling', StandardScaler())])

In [50]:
X_train.head()

Car_Name  Year  Present_Price  Kms_Driven Fuel_Type  \
184           Bajaj Pulsar 150  2008          0.750       26000    Petrol   
132          Bajaj Avenger 220  2017          0.950        3500    Petrol   
194           Hero  CBZ Xtreme  2008          0.787       50000    Petrol   
75                     etios g  2015          6.800       36000    Petrol   
111  Royal Enfield Thunder 350  2016          1.500        8700    Petrol   

    Seller_Type Transmission  Owner  
184  Individual       Manual      1  
132  Individual       Manual      0  
194  Individual       Manual      0  
75       Dealer       Manual      0  
111  Individual       Manual      0

In [51]:
pipe.fit_transform(X_train[["Fuel_Type", "Seller_Type"]])

Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  Seller_Type_Dealer  \
184       -0.09167         -0.480384          0.493481           -1.338170   
132       -0.09167         -0.480384          0.493481           -1.338170   
194       -0.09167         -0.480384          0.493481           -1.338170   
75        -0.09167         -0.480384          0.493481            0.747289   
111       -0.09167         -0.480384          0.493481           -1.338170   
..             ...               ...               ...                 ...   
188       -0.09167         -0.480384          0.493481           -1.338170   
71        -0.09167          2.081666         -2.026421            0.747289   
106       -0.09167         -0.480384          0.493481           -1.338170   
270       -0.09167         -0.480384          0.493481            0.747289   
102       -0.09167         -0.480384          0.493481           -1.338170   

     Seller_Type_Individual  
184                1.338170  
132                1.338170  
194                1.338170  
75                -0.747289  
111                1.338170  
..                      ...  
188                1.338170  
71                -0.747289  
106                1.338170  
270               -0.747289  
102                1.338170  

[240 rows x 5 columns]

In [57]:
from sklearn.compose import ColumnTransformer

trf = [("median", SimpleImputer(missing_values=np.nan, strategy='median'), ['Kms_Driven']),
       ("mode", SimpleImputer(missing_values=np.nan, strategy='most_frequent'), ['Fuel_Type']),
       ("mean", SimpleImputer(missing_values=np.nan, strategy='mean'), ['Owner'])]


ct = ColumnTransformer(transformers=trf, remainder="passthrough").set_output(transform="pandas")
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('median', SimpleImputer(strategy='median'),
                                 ['Kms_Driven']),
                                ('mode',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Fuel_Type']),
                                ('mean', SimpleImputer(), ['Owner'])])

In [59]:
df2 = ct.fit_transform(X_train)

In [60]:
df2.head()

median__Kms_Driven mode__Fuel_Type  mean__Owner  \
184             26000.0          Petrol          1.0   
132              3500.0          Petrol          0.0   
194             50000.0          Petrol          0.0   
75              36000.0          Petrol          0.0   
111              8700.0          Petrol          0.0   

           remainder__Car_Name  remainder__Year  remainder__Present_Price  \
184           Bajaj Pulsar 150             2008                     0.750   
132          Bajaj Avenger 220             2017                     0.950   
194           Hero  CBZ Xtreme             2008                     0.787   
75                     etios g             2015                     6.800   
111  Royal Enfield Thunder 350             2016                     1.500   

    remainder__Seller_Type remainder__Transmission  
184             Individual                  Manual  
132             Individual                  Manual  
194             Individual                  Manual  
75                  Dealer                  Manual  
111             Individual                  Manual