In [46]:
import numpy as np
import pandas as pd

In [47]:
df = pd.read_csv("car data.csv")

In [48]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [49]:
import sklearn
sklearn.__version__

'1.6.1'

In [50]:
X = df.drop("Selling_Price", axis="columns")
y = df['Selling_Price']

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [52]:
X_train.shape

(240, 8)

In [53]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
oe

OrdinalEncoder()

In [54]:
X_train['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [55]:
oe.fit_transform(X_train[['Transmission']]) # [[]] this is used, as only matrix expected

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [56]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
ohe.fit_transform(X_train[['Fuel_Type']])

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [57]:
ohe.categories_

[array(['CNG', 'Diesel', 'Petrol'], dtype=object)]

In [58]:
from sklearn.impute import SimpleImputer
# si = SimpleImputer(strategy='mean', missing_values=np.nan)
mean_si = SimpleImputer(missing_values=np.nan, strategy='mean')
mean_si

SimpleImputer()

In [59]:
X_train.isnull().sum()

Car_Name         0
Year             0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [62]:
mean_si.get_params()

{'add_indicator': False,
 'copy': True,
 'fill_value': None,
 'keep_empty_features': False,
 'missing_values': nan,
 'strategy': 'mean'}

In [63]:
med_si = SimpleImputer(missing_values=np.nan, strategy='median')
med_si

SimpleImputer(strategy='median')

In [64]:
med_si.fit_transform(X_train[['Kms_Driven']])

array([[ 26000.],
       [  3500.],
       [ 50000.],
       [ 36000.],
       [  8700.],
       [ 41000.],
       [ 40000.],
       [ 18796.],
       [ 75000.],
       [ 51439.],
       [ 50000.],
       [ 28569.],
       [ 40534.],
       [ 23709.],
       [ 35000.],
       [  5000.],
       [ 12900.],
       [ 35000.],
       [ 21780.],
       [ 14465.],
       [ 31604.],
       [197176.],
       [ 11000.],
       [ 53460.],
       [   500.],
       [  5400.],
       [ 41442.],
       [ 50000.],
       [ 89000.],
       [ 17000.],
       [  1900.],
       [ 56001.],
       [ 43000.],
       [  2135.],
       [500000.],
       [ 87934.],
       [ 88000.],
       [ 24678.],
       [127000.],
       [ 41678.],
       [ 40000.],
       [ 44000.],
       [ 69562.],
       [ 59000.],
       [ 22517.],
       [ 12000.],
       [ 54200.],
       [ 30000.],
       [ 13000.],
       [ 16002.],
       [ 25000.],
       [ 35500.],
       [ 21000.],
       [ 29000.],
       [ 11849.],
       [ 4

In [65]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler() # (value - mean)/sigma
ss

StandardScaler()

In [66]:
ss.fit_transform(X_train[['Kms_Driven']])

array([[-0.27555466],
       [-0.81428242],
       [ 0.29908829],
       [-0.0361201 ],
       [-0.68977645],
       [ 0.08359718],
       [ 0.05965372],
       [-0.44804332],
       [ 0.89767469],
       [ 0.33354292],
       [ 0.29908829],
       [-0.21404392],
       [ 0.07243953],
       [-0.33040912],
       [-0.06006356],
       [-0.77836724],
       [-0.58921394],
       [-0.06006356],
       [-0.37659605],
       [-0.55174243],
       [-0.14137553],
       [ 3.82299039],
       [-0.6347065 ],
       [ 0.38193264],
       [-0.88611279],
       [-0.76878986],
       [ 0.09418019],
       [ 0.29908829],
       [ 1.23288307],
       [-0.49104577],
       [-0.85259195],
       [ 0.44277297],
       [ 0.13148409],
       [-0.84696524],
       [11.07364355],
       [ 1.20735935],
       [ 1.20893962],
       [-0.30720791],
       [ 2.14273441],
       [ 0.09983084],
       [ 0.05965372],
       [ 0.15542755],
       [ 0.76747017],
       [ 0.51457939],
       [-0.35894972],
       [-0

In [67]:
from sklearn.pipeline import Pipeline

In [68]:
st = [("Impute_mode", SimpleImputer(missing_values=np.nan, strategy="most_frequent")), 
      ("OHE", OneHotEncoder(sparse_output=False)), 
      ("Scaling", StandardScaler())]

pipe = Pipeline(steps = st).set_output(transform="pandas")
pipe


Pipeline(steps=[('Impute_mode', SimpleImputer(strategy='most_frequent')),
                ('OHE', OneHotEncoder(sparse_output=False)),
                ('Scaling', StandardScaler())])

In [69]:
X_train.head()

Car_Name  Year  Present_Price  Kms_Driven Fuel_Type  \
184           Bajaj Pulsar 150  2008          0.750       26000    Petrol   
132          Bajaj Avenger 220  2017          0.950        3500    Petrol   
194           Hero  CBZ Xtreme  2008          0.787       50000    Petrol   
75                     etios g  2015          6.800       36000    Petrol   
111  Royal Enfield Thunder 350  2016          1.500        8700    Petrol   

    Seller_Type Transmission  Owner  
184  Individual       Manual      1  
132  Individual       Manual      0  
194  Individual       Manual      0  
75       Dealer       Manual      0  
111  Individual       Manual      0

In [70]:
pipe.fit_transform(X_train[["Fuel_Type", "Seller_Type"]])

Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  Seller_Type_Dealer  \
184       -0.09167         -0.480384          0.493481           -1.338170   
132       -0.09167         -0.480384          0.493481           -1.338170   
194       -0.09167         -0.480384          0.493481           -1.338170   
75        -0.09167         -0.480384          0.493481            0.747289   
111       -0.09167         -0.480384          0.493481           -1.338170   
..             ...               ...               ...                 ...   
188       -0.09167         -0.480384          0.493481           -1.338170   
71        -0.09167          2.081666         -2.026421            0.747289   
106       -0.09167         -0.480384          0.493481           -1.338170   
270       -0.09167         -0.480384          0.493481            0.747289   
102       -0.09167         -0.480384          0.493481           -1.338170   

     Seller_Type_Individual  
184                1.338170  
132                1.338170  
194                1.338170  
75                -0.747289  
111                1.338170  
..                      ...  
188                1.338170  
71                -0.747289  
106                1.338170  
270               -0.747289  
102                1.338170  

[240 rows x 5 columns]

In [71]:
from sklearn.compose import ColumnTransformer

imputing_trf = [("median", SimpleImputer(missing_values=np.nan, strategy='median'), ['Kms_Driven']),
       ("mode", SimpleImputer(missing_values=np.nan, strategy='most_frequent'), ['Fuel_Type']),
       ("mean", SimpleImputer(missing_values=np.nan, strategy='mean'), ['Owner'])]


imputing_cols = ColumnTransformer(transformers=trf, remainder="passthrough", verbose_feature_names_out=False).set_output(transform="pandas")
imputing_cols

ColumnTransformer(remainder='passthrough',
                  transformers=[('median', SimpleImputer(strategy='median'),
                                 ['Kms_Driven']),
                                ('mode',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Fuel_Type']),
                                ('mean', SimpleImputer(), ['Owner'])],
                  verbose_feature_names_out=False)

In [80]:
df2 = imputing_cols.fit_transform(X_train)

In [81]:
df2.head()

Kms_Driven Fuel_Type  Owner                   Car_Name  Year  \
184     26000.0    Petrol    1.0           Bajaj Pulsar 150  2008   
132      3500.0    Petrol    0.0          Bajaj Avenger 220  2017   
194     50000.0    Petrol    0.0           Hero  CBZ Xtreme  2008   
75      36000.0    Petrol    0.0                    etios g  2015   
111      8700.0    Petrol    0.0  Royal Enfield Thunder 350  2016   

     Present_Price Seller_Type Transmission  
184          0.750  Individual       Manual  
132          0.950  Individual       Manual  
194          0.787  Individual       Manual  
75           6.800      Dealer       Manual  
111          1.500  Individual       Manual

In [74]:
X_train.head()

Car_Name  Year  Present_Price  Kms_Driven Fuel_Type  \
184           Bajaj Pulsar 150  2008          0.750       26000    Petrol   
132          Bajaj Avenger 220  2017          0.950        3500    Petrol   
194           Hero  CBZ Xtreme  2008          0.787       50000    Petrol   
75                     etios g  2015          6.800       36000    Petrol   
111  Royal Enfield Thunder 350  2016          1.500        8700    Petrol   

    Seller_Type Transmission  Owner  
184  Individual       Manual      1  
132  Individual       Manual      0  
194  Individual       Manual      0  
75       Dealer       Manual      0  
111  Individual       Manual      0

In [75]:
encoding_trf = [("OHE", OneHotEncoder(sparse_output=False), ["Fuel_Type", "Seller_Type", "Transmission"]),
                ("OE", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), ["Car_Name"])]
encoded_col = ColumnTransformer(transformers=encoding_trf, remainder="passthrough").set_output(transform="pandas")
encoded_col

ColumnTransformer(remainder='passthrough',
                  transformers=[('OHE', OneHotEncoder(sparse_output=False),
                                 ['Fuel_Type', 'Seller_Type', 'Transmission']),
                                ('OE',
                                 OrdinalEncoder(handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['Car_Name'])])

In [76]:
df3 = encoded_col.fit_transform(X_train)
df3.head()

OHE__Fuel_Type_CNG  OHE__Fuel_Type_Diesel  OHE__Fuel_Type_Petrol  \
184                 0.0                    0.0                    1.0   
132                 0.0                    0.0                    1.0   
194                 0.0                    0.0                    1.0   
75                  0.0                    0.0                    1.0   
111                 0.0                    0.0                    1.0   

     OHE__Seller_Type_Dealer  OHE__Seller_Type_Individual  \
184                      0.0                          1.0   
132                      0.0                          1.0   
194                      0.0                          1.0   
75                       1.0                          0.0   
111                      0.0                          1.0   

     OHE__Transmission_Automatic  OHE__Transmission_Manual  OE__Car_Name  \
184                          0.0                       1.0          12.0   
132                          0.0                       1.0           5.0   
194                          0.0                       1.0          16.0   
75                           0.0                       1.0          70.0   
111                          0.0                       1.0          43.0   

     remainder__Year  remainder__Present_Price  remainder__Kms_Driven  \
184             2008                     0.750                  26000   
132             2017                     0.950                   3500   
194             2008                     0.787                  50000   
75              2015                     6.800                  36000   
111             2016                     1.500                   8700   

     remainder__Owner  
184                 1  
132                 0  
194                 0  
75                  0  
111                 0

In [77]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, 184 to 102
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   OHE__Fuel_Type_CNG           240 non-null    float64
 1   OHE__Fuel_Type_Diesel        240 non-null    float64
 2   OHE__Fuel_Type_Petrol        240 non-null    float64
 3   OHE__Seller_Type_Dealer      240 non-null    float64
 4   OHE__Seller_Type_Individual  240 non-null    float64
 5   OHE__Transmission_Automatic  240 non-null    float64
 6   OHE__Transmission_Manual     240 non-null    float64
 7   OE__Car_Name                 240 non-null    float64
 8   remainder__Year              240 non-null    int64  
 9   remainder__Present_Price     240 non-null    float64
 10  remainder__Kms_Driven        240 non-null    int64  
 11  remainder__Owner             240 non-null    int64  
dtypes: float64(9), int64(3)
memory usage: 24.4 KB


In [82]:
stp = [("Imputing", imputing_cols),
       ("Encoding", encoded_col),
       ("Scaling", StandardScaler())]

pipe = Pipeline(steps=stp).set_output(transform="pandas")
pipe

/home/anjali/Desktop/MLP Course/menv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('Imputing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('median',
                                                  SimpleImputer(strategy='median'),
                                                  ['Kms_Driven']),
                                                 ('mode',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['Fuel_Type']),
                                                 ('mean', SimpleImputer(),
                                                  ['Owner'])],
                                   verbose_feature_names_out=False)),
                ('Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Fuel_Type', 'Seller_Type',
                                                   'Transmission']),
                                                 ('OE',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['Car_Name'])])),
                ('Scaling', StandardScaler())])

In [87]:
df4 = pipe.fit_transform(X_train)

In [92]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=5, step=1).set_output(transform="pandas")

In [93]:
selector = selector.fit(df4, y_train)
selector.support_

array([False,  True, False,  True, False, False, False, False,  True,
       False,  True,  True])

In [94]:
selector.ranking_

array([6, 1, 4, 1, 3, 2, 5, 7, 1, 8, 1, 1])

In [95]:
selector.transform(df4)

OHE__Fuel_Type_Diesel  OHE__Seller_Type_Dealer  remainder__Kms_Driven  \
184              -0.480384                -1.338170              -0.275555   
132              -0.480384                -1.338170              -0.814282   
194              -0.480384                -1.338170               0.299088   
75               -0.480384                 0.747289              -0.036120   
111              -0.480384                -1.338170              -0.689776   
..                     ...                      ...                    ...   
188              -0.480384                -1.338170              -0.467102   
71                2.081666                 0.747289               0.179371   
106              -0.480384                -1.338170              -0.503017   
270              -0.480384                 0.747289               0.762179   
102              -0.480384                -1.338170              -0.802311   

     remainder__Year  remainder__Present_Price  
184        -1.969861                 -0.753596  
132         1.156443                 -0.731307  
194        -1.969861                 -0.749472  
75          0.461709                 -0.079351  
111         0.809076                 -0.670012  
..               ...                       ...  
188        -0.233025                 -0.773656  
71         -0.927760                  0.553660  
106         0.114342                 -0.452693  
270        -0.927760                  0.277275  
102         1.156443                 -0.638807  

[240 rows x 5 columns]

In [96]:
selector.estimator_.coef_

array([[ 0.23664213,  0.50987489, -0.4094387 ,  0.61055838,  4.58347539]])

In [97]:
estimator.fit(df4, y_train)

SVR(kernel='linear')

In [98]:
estimator.coef_

array([[-0.0895172 ,  0.15332253, -0.13029414,  0.24860377, -0.24860377,
         0.13829025, -0.13829025,  0.06116677, -0.36102   , -0.03619728,
         0.62373641,  4.30915357]])

In [99]:
np.sort(np.abs(estimator.coef_))

array([[0.03619728, 0.06116677, 0.0895172 , 0.13029414, 0.13829025,
        0.13829025, 0.15332253, 0.24860377, 0.24860377, 0.36102   ,
        0.62373641, 4.30915357]])

In [100]:
stp = [("Imputing", imputing_cols),
       ("Encoding", encoded_col),
       ("Scaling", StandardScaler()),
       ("Feature Selection", selector)]

pipe = Pipeline(steps=stp).set_output(transform="pandas")
pipe

/home/anjali/Desktop/MLP Course/menv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('Imputing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('median',
                                                  SimpleImputer(strategy='median'),
                                                  ['Kms_Driven']),
                                                 ('mode',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['Fuel_Type']),
                                                 ('mean', SimpleImputer(),
                                                  ['Owner'])],
                                   verbose_feature_names_out=False)),
                ('Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Fuel_Type', 'Seller_Type',
                                                   'Transmission']),
                                                 ('OE',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['Car_Name'])])),
                ('Scaling', StandardScaler()),
                ('Feature Selection',
                 RFE(estimator=SVR(kernel='linear'), n_features_to_select=5))])

In [101]:
pipe.fit(X_train, y_train)

/home/anjali/Desktop/MLP Course/menv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('Imputing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('median',
                                                  SimpleImputer(strategy='median'),
                                                  ['Kms_Driven']),
                                                 ('mode',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['Fuel_Type']),
                                                 ('mean', SimpleImputer(),
                                                  ['Owner'])],
                                   verbose_feature_names_out=False)),
                ('Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Fuel_Type', 'Seller_Type',
                                                   'Transmission']),
                                                 ('OE',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['Car_Name'])])),
                ('Scaling', StandardScaler()),
                ('Feature Selection',
                 RFE(estimator=SVR(kernel='linear'), n_features_to_select=5))])

In [105]:
X_trfm = pipe.transform(X_train)
X_trfm

OHE__Fuel_Type_Diesel  OHE__Seller_Type_Dealer  remainder__Kms_Driven  \
184              -0.480384                -1.338170              -0.275555   
132              -0.480384                -1.338170              -0.814282   
194              -0.480384                -1.338170               0.299088   
75               -0.480384                 0.747289              -0.036120   
111              -0.480384                -1.338170              -0.689776   
..                     ...                      ...                    ...   
188              -0.480384                -1.338170              -0.467102   
71                2.081666                 0.747289               0.179371   
106              -0.480384                -1.338170              -0.503017   
270              -0.480384                 0.747289               0.762179   
102              -0.480384                -1.338170              -0.802311   

     remainder__Year  remainder__Present_Price  
184        -1.969861                 -0.753596  
132         1.156443                 -0.731307  
194        -1.969861                 -0.749472  
75          0.461709                 -0.079351  
111         0.809076                 -0.670012  
..               ...                       ...  
188        -0.233025                 -0.773656  
71         -0.927760                  0.553660  
106         0.114342                 -0.452693  
270        -0.927760                  0.277275  
102         1.156443                 -0.638807  

[240 rows x 5 columns]

In [106]:
pipe.transform(X_test)

OHE__Fuel_Type_Diesel  OHE__Seller_Type_Dealer  remainder__Kms_Driven  \
177              -0.480384                -1.338170              -0.323442   
289              -0.480384                 0.747289              -0.635185   
228               2.081666                 0.747289               0.538523   
198              -0.480384                -1.338170              -0.060064   
60               -0.480384                 0.747289               0.059678   
..                     ...                      ...                    ...   
234              -0.480384                 0.747289              -0.790531   
296               2.081666                 0.747289              -0.084294   
281              -0.480384                 0.747289               0.310007   
285              -0.480384                 0.747289              -0.537520   
182              -0.480384                -1.338170              -0.179781   

     remainder__Year  remainder__Present_Price  
177         0.809076                 -0.773656  
289         0.809076                  0.678479  
228        -0.580393                  0.210408  
198        -0.927760                 -0.773656  
60         -0.233025                  1.236821  
..               ...                       ...  
234         0.461709                 -0.201941  
296         0.809076                  0.455588  
281        -2.664595                  0.009806  
285         0.809076                  0.110107  
182        -0.233025                 -0.772542  

[61 rows x 5 columns]

In [107]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [108]:
stp = [("Imputing", imputing_cols),
       ("Encoding", encoded_col),
       ("Scaling", StandardScaler()),
       ("Feature Selection", selector),
       ("Model", LinearRegression())]

pipe = Pipeline(steps=stp).set_output(transform="pandas")
pipe

Pipeline(steps=[('Imputing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('median',
                                                  SimpleImputer(strategy='median'),
                                                  ['Kms_Driven']),
                                                 ('mode',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['Fuel_Type']),
                                                 ('mean', SimpleImputer(),
                                                  ['Owner'])],
                                   verbose_feature_names_out=False)),
                ('Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Fuel_Type', 'Seller_Type',
                                                   'Transmission']),
                                                 ('OE',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['Car_Name'])])),
                ('Scaling', StandardScaler()),
                ('Feature Selection',
                 RFE(estimator=SVR(kernel='linear'), n_features_to_select=5)),
                ('Model', LinearRegression())])

In [109]:
pipe.fit(X_train, y_train)

/home/anjali/Desktop/MLP Course/menv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('Imputing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('median',
                                                  SimpleImputer(strategy='median'),
                                                  ['Kms_Driven']),
                                                 ('mode',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['Fuel_Type']),
                                                 ('mean', SimpleImputer(),
                                                  ['Owner'])],
                                   verbose_feature_names_out=False)),
                ('Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Fuel_Type', 'Seller_Type',
                                                   'Transmission']),
                                                 ('OE',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['Car_Name'])])),
                ('Scaling', StandardScaler()),
                ('Feature Selection',
                 RFE(estimator=SVR(kernel='linear'), n_features_to_select=5)),
                ('Model', LinearRegression())])

In [112]:
pipe[-1]

LinearRegression()

In [111]:
pipe[-1].coef_

array([ 0.6911164 ,  0.51058642, -0.16176864,  1.12360198,  4.05275155])

In [113]:
pipe[-1].intercept_

np.float64(4.642291666666673)

In [115]:
pipe.predict(X_test.sample(2, random_state=42))

array([1.45300541, 7.59841259])

In [118]:
parameter = {
    "kernel" : ("linear", "poly", "rbf", "sigmoid", "precomputed"),
    "C" : (0, 0.25, 1)
}
parameter
# 15 models will get trained using this parameter grid

{'kernel': ('linear', 'poly', 'rbf', 'sigmoid', 'precomputed'),
 'C': (0, 0.25, 1)}

In [121]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    SVR(), param_grid=parameter, cv=3
)
grid

GridSearchCV(cv=3, estimator=SVR(),
             param_grid={'C': (0, 0.25, 1),
                         'kernel': ('linear', 'poly', 'rbf', 'sigmoid',
                                    'precomputed')})